# Netlify configuration file

[build]
  publish = "/"
  # If you had a build command, you would include it here
  # command = "npm run build"
    functions = "netlify/functions"

# Headers to set on the site
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Content Security Policy temporarily removed for testing
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Cache Control
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com https://maps.googleapis.com 'unsafe-inline'; style-src 'self' https://cdnjs.cloudflare.com 'unsafe-inline'; img-src 'self' https://maps.googleapis.com https://maps.gstatic.com data:; connect-src 'self' https://maps.googleapis.com; frame-src 'none'; font-src 'self' https://cdnjs.cloudflare.com;"




[build.environment]
  GOOGLE_MAPS_API_KEY = "${GOOGLE_MAPS_API_KEY}"


