# Netlify configuration file

[build]
  publish = "/"
  # If you had a build command, you would include it here
  # command = "npm run build"

# Headers to set on the site
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Updated Content-Security-Policy to allow Google Maps and related services
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' cdnjs.cloudflare.com cdn.tailwindcss.com maps.googleapis.com *.google.com *.gstatic.com; style-src 'self' 'unsafe-inline' cdnjs.cloudflare.com cdn.tailwindcss.com fonts.googleapis.com *.gstatic.com; img-src 'self' data: maps.googleapis.com *.googleapis.com *.gstatic.com *.google.com; font-src 'self' fonts.gstatic.com; connect-src 'self' maps.googleapis.com *.google.com; frame-src 'self'"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache Control
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[build.environment]
  GOOGLE_MAPS_API_KEY = "AIzaSyCancy_vwbDbYZavxDjtpL7NW4lYl8Tkmk"
